### ISSUE TITLE
Workflow to use, after install

### ISSUE THREAD

**Issue by vincsb** [BeAPI/beapi-frontend-framework#2]
Hi there!

I'm testing your framework to see how you works on your projects, by curiosity. Everything works fine, and the install guide was perfect.

Now i'm trying to build a little theme based on BFF, but I don't see how you works with the template files. If I understand, you have a _/html_ folder with the basics files (_header.php_, _style.css_ + your custom hierarchy).

But, when you start a theme, you flush the _index.php_ file with the [File Directory Listing Script](https://github.com/halgatewood/file-directory-list/) and you start your front-end work on this _/html_ folder? Do you drop the files that you don't use, and you make all the dynamic parts (template tags, ACF, Gravity Forms...) after all html work?

Can I have more details on your Workflow?

This is not a real issue, it's more a question to understand how you use it on the pure templating part.

Thanks for you help, and your share!

**Comment by Cocola** [comment]
Hello!
BFF is a strictly html oriented framework. It help us to build static templates in the html folder.
Once they are done, Wordpress developers take our front-end job in order to make the real template-part, custom post type etc.
But we are thinking of implementing some basics wp stuffs into our starter in the future.
Stay in touch !
Best

**Comment by vincsb** [comment]
Hi!
Ok, I understand now, thanks for your answer, I will follow the development on!
Have a good day!
